### ISSUE TITLE
updateData 'Cannot update existing geojson data'

### ISSUE THREAD

**Issue by rtalon83** [maplibre/maplibre-gl-js#2920]
**maplibre-gl-js version**: 3.2.0

**browser**: Chrome Versión 114.0.5735.248 (Build oficial) (64 bits)

### Steps to Trigger Behavior

 1. Create new source with a lot of features
 2. Add new feature in this source previously rendered
 3. call function
 
`const currentSource = this.map.getSource(sourceId);
currentSource.updateData({
            add: [newFeature]
        });`

### Expected Behavior
The new feature is showed in the map. This works using setData(source + newFeature)

### Actual Behavior
Cannot update existing geojson data in 'name_source'

### Investigation
`else if (params.dataDiff) {
                if (this._dataUpdateable) {
                    applySourceDiff(this._dataUpdateable, params.dataDiff, promoteId);
                    callback(null, { type: 'FeatureCollection', features: Array.from(this._dataUpdateable.values()) });
                }
                else {
                    callback(new Error(`Cannot update existing geojson data in ${params.source}`));
                }
            }
            else {
                callback(new Error(`Input data given to '${params.source}' is not a valid GeoJSON object.`));`

The variable this._dataUpdateable is null

**Comment by HarelM** [comment]
Can you provide a jsbin/codepen/stackblitz reproduction?

**Comment by rtalon83** [comment]
Yes!

https://codepen.io/rtalon83/pen/abQRYrG?editors=1111

Press click in map to updateData

**Comment by HarelM** [comment]
You need to set ID for features and set `promoteId` in the source definitions, I think.

**Comment by rtalon83** [comment]
Fixed!!

Yes, the problem is the unique ID, `promoteId` has nothing to do with the problem. In my original code I had `generateId: true` then I've removed this param and insert own unique ID in my features (in this case are string).
Now it works correctly.

**Comment by HarelM** [comment]
Feel free to update the method/type documentation, preferably with an example, also worth adding an example page I think.

**Comment by truongvan** [comment]
I believe that the setData method from the example at https://maplibre.org/maplibre-gl-js/docs/examples/animate-a-line/ functions similarly to updateData.

**Comment by HarelM** [comment]
The example linked above is not an incremental update, but rather replace-all kind of update.
So it's not the same...

**Comment by Ivan-beep** [comment]
Hi,

First of all, thanks to all mainteners to provide this amazing library. Big up for you all 👏 
Then sorry to bring up the issue, but I don't think it's solved. Indeed, if we use the `generateId: true` option, it will be impossible to use `updateData()`.
IMHO the fix seems simple because when we use the `generateId` option, the first feature will have the ID value set to 0, but the condition in the `isUpdateableGeoJSON()` method performs a soft condition.

```typescript
    // a feature collection can be updated if every feature has an id, and the ids are all unique
    // this prevents us from silently dropping features if ids get reused
    if (data.type === 'FeatureCollection') {
        const seenIds = new Set<GeoJSONFeatureId>();
        for (const feature of data.features) {
            const id = getFeatureId(feature, promoteId);
            if (id == null) {   // the id equals to 0 will fall into this condition
                return false;
            }

            if (seenIds.has(id)) {
                return false;
            }

            seenIds.add(id);
        }

        return true;
    }

    return false;

```

**Comment by Cyrille37** [comment]
Here a @rtalon83 modified version which change a Point position :
- https://codepen.io/cyrille37/pen/xbGzmpO?editors=0011

#1605 source.updateData() works :-)
